### ISSUE TITLE
google Analytics: Price amount is not tracked

### ISSUE THREAD

**Issue by Rah1x** [woothemes/woocommerce-google-analytics-integration#49]
I have a site on `Wordpress` and its using `wooCommerce`. For the `Ecommerce tracking` in the `google Analytics`, I have used the additional plugin `WooCommerce Google Analytics Integration`
https://wordpress.org/plugins/woocommerce-google-analytics-integration/

Now the Ecommerce Tracking is going just fine, but its NOT picking the price / amount of the Orders and is always showing 0.0.

Since, its wordpress, I dont want to go into the code and change the files to have GA work. 

Any idea how to solve this?

**Comment by justinshreve** [comment]
I'm not able to reproduce this on a clean install. Could you let me know which version of WooCommerce and WooCommerce Google Analytics Integration you are using?

Is this all products or does the order include a specific type of product (like a variable product for example)? 

And to double check - when you go to GA, and then Conversions > eCommerce > Transactions, do you see the products in the order like below, just with 0 in the revenue?

![](https://cldup.com/cROifEJgg8-3000x3000.png) 

Thanks! Just trying to narrow this down to see if I can reproduce.

**Comment by Rah1x** [comment]
Thanks for looking into it. Here are the details:

WP: 4.2.2
WooCommerce Plugin: 2.3.13
WooCommerce Google Analytics Integration Plugin: 1.3.0
Currency used = PKR

And yea, at GA its always '0' at the revenue.. 

See this:
![1](https://cloud.githubusercontent.com/assets/841857/8565549/0d65a3cc-2570-11e5-845e-cdbd900bb34d.png)

**Comment by Rah1x** [comment]
Hello? did you solve it yet?

**Comment by justinshreve** [comment]
Hi Rah1x, sorry for the delay - I was out.

I did some more investigation, set my currency as PKR both in GA and in WooCommerce (using some code to add it to the currency selection), and did a few test transactions. I also tested a couple different versions and can't seem to reproduce the issue.

![](https://cldup.com/4JZDSdm3Ox-3000x3000.png)

My next question to help narrow this down - how are you adding the currency to WooCommerce (since PKR isn't one of the default currencies)? A specific plugin? Custom code?

**Comment by justinshreve** [comment]
I haven't been able to reproduce this with PKR or any other currency. I'm going to close for now. However, if you are still experiencing issues please go to *WooCommerce > System Status > Get System Report* and email me the log at justin@automattic.com (don't post it here since it can contain sensitive info and this is a public repo).
