### ISSUE TITLE
Missing ecommerce transactions

### ISSUE THREAD

**Issue by DaveLindberg** [woothemes/woocommerce-google-analytics-integration#60]
Just wanted to file an alert that our ecommerce tracking flatlined and stopped functioning on July 13. Similar in some respects to issue #41. 

In testing the issue, after disabling the extension and re-enabling it, the transaction data resumed flowing properly back into GA. So we're good, but I wanted to file this as a possible heads up. 

We're running v1.3.0,  which was last updated 9 months ago according to the software's detail page. 

There are no changes in Google Analytics account history. Here's our current Woo settings report: 

### WordPress Environment ###

Home URL: https://hummelgifts.com
Site URL: https://hummelgifts.com
WC Version: 2.3.13
WC Database Version: 2.3.13
Log Directory Writable: /home/hummelgifts/public_html/wp-content/uploads/wc-logs/
WP Version: 4.2.4
WP Multisite: –
WP Memory Limit: 96 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.5.23
PHP Post Max Size: 300 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.42
Max Upload Size: 300 MB
Default Timezone is UTC: 
fsockopen/cURL: 
SoapClient: 
DOMDocument: 
GZip: 
Remote Post: 
Remote Get: 

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Active Plugins (35) ###

Gravity Forms: by rocketgenius – 1.9.12.1
Akismet: by Automattic – 3.1.3
All In One SEO Pack: by Michael Torbert – 2.2.7.1
BackupBuddy: by iThemes – 6.2.2.1
BM Custom Login: by Ben Gillbanks – 1.8.2
Chimpy Lite - MailChimp WordPress Plugin: by RightPress – 1.0.3
Contact Form 7: by Takayuki Miyoshi – 4.2.2
EWWW Image Optimizer: by Shane Bishop – 2.5.0
Anti-Malware and Brute-Force Security by ELI: by Eli Scheetz – 4.15.30
Gravity Forms Placeholder Add-On: by Able Engine
William Wilkerson – 1.1.0

Gravity Forms Authorize.Net Add-On: by rocketgenius – 2.1
Gravity Forms Coupons Add-On: by rocketgenius – 2.1
Gravity Forms Logging Add-On: by rocketgenius – 1.0
InfiniteWP - Client: by Revmakx – 1.3.16
Search & Replace: by Frank Bültge – 2.7.1
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1
Stop Spam Comments: by Pino Ceniccola – 0.2
WooCommerce Table Rate Shipping by Mangohour: by mangohour – 1.1.0
Webgility: by Webgility – v321
WooCommerce Checkout Field Editor: by WooThemes / Mike Jolley / Patrick Garman – 1.4.3
WooCommerce Customer/Order CSV Export: by WooThemes / SkyVerge – 3.10.0
WooCommerce Free Gift Coupons: by Kathy Darling – 1.0.5
WooCommerce Authorize.net CIM Gateway: by WooThemes / SkyVerge – 2.0.1
Woocommerce Adwords Conversion Tracking: by Víctor Falcón – 1.0.1
WooCommerce Google Analytics Integration: by WooThemes – 1.3.0
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.5.7

WooCommerce Sales MIS Report: by Infosoft Consultant – 2.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.19
WooCommerce Google Product Feed: by Lee Willis – 4.0.3
WooCommerce Smart Coupons: by Store Apps – 3.0.2
WooCommerce: by WooThemes – 2.3.13
WooThemes Helper: by WooThemes – 1.5.9
Wordfence Security: by Wordfence – 6.0.14
WordPress Gzip Compression: by James Socol – 1.0
WordPress HTTPS: by Mike Ems – 3.3.6

### Settings ###

API Enabled: 
Taxes Enabled: 
Shipping Enabled: 
Force SSL: 
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### WC Pages ###

Shop Base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #9 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Merchant
Version: 1.2.3 – 1.5.1 is available
Author URL: http://www.woothemes.com
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: 

### Templates ###

Overrides: merchant/woocommerce/archive-product.php
merchant/woocommerce/cart/mini-cart.php
merchant/woocommerce/content-product.php
merchant/woocommerce/single-product/product-image.php

**Comment by justinshreve** [comment]
Did things continue to work after the upgrade to WC 2.3.13 or is it possible that the upgrade happened around when things broke on the 13th? Thanks for the comprehensive debug info, by the way.

**Comment by DaveLindberg** [comment]
Possible the upgrade occurred around July 13, but I can't tell. Where can I find the system log?

**Comment by justinshreve** [comment]
I don't think plugin updates log any data like that unfortunately. Thanks again for your info - I'll try to investigate if anything in WC 2.3.13 could have caused data to stop tracking in some instances.

**Comment by justinshreve** [comment]
I've been unable to reproduce this and nothing immediately jumps out at me from your system information. If the link breaks again and you can note any circumstances which might be related (such as another upgrade around the same time) please reply here and let me know.

**Comment by Niknation** [comment]
Hello! I seem to have a similar problem as the one @DaveLindberg has mentioned. 

My ecommerce data has flatlined every since August 2015. I believe this coincides with when we updated wordpress. 

My System Status data is shown below. @justinshreve is there any possible troubleshooting I could be doing to solve this?

### WordPress Environment ###

Home URL: https://www.resumewriter.sg
Site URL: https://www.resumewriter.sg
WC Version: 2.3.9
WC Database Version: 2.3.9
Log Directory Writable: /home/resumewriter/html/wp-content/uploads/wc-logs/
WP Version: 4.2.5
WP Multisite: –
WP Memory Limit: 64 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.9.5
PHP Version: 5.6.99-hhvm
PHP Post Max Size: 
PHP Time Limit: 0
PHP Max Input Vars: 
SUHOSIN Installed: –
MySQL Version: 5.5.5
Max Upload Size: 
Default Timezone is UTC: 
fsockopen/cURL: 
SoapClient: 
DOMDocument: 
GZip: 
Remote Post: 
Remote Get: ✕							wp_remote_get() failed. The WooCommerce plugin updater won't work with your server. Contact your hosting provider. Error: Operation timed out after 2001 milliseconds with 0 bytes received

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Active Plugins (32) ###

Add Meta Tags: by George Notaras – 2.9.1
All In One SEO Pack: by Michael Torbert – 2.2.7.2
BackupBuddy: by iThemes – 6.2.1.1
Contact Form DB: by Michael Simpson – 2.9.7
Contact Form 7: by Takayuki Miyoshi – 4.2.2
Google Tag Manager for Wordpress: by Thomas Geiger – 1.1.1
Facebook Conversion Pixel: by Kellen Mace – 1.3.1
Google XML Sitemaps: by Arne Brachhold – 4.0.8
MailChimp for WordPress Lite: by ibericode – 2.3.7
Mailgun Email Validator: by Jesin – 1.2.2
Monarch Plugin: by Elegant Themes – 1.2.1
Optimizely: by Optimizely Inc. – 3.7.1
OptinMonster API: by Thomas Griffin – 1.1.2.3
Oxygenna Bootstrap Plugin: by Oxygenna.com – 1.1.1
Oxygenna Theme Framework: by Oxygenna.com – 1.4.4
Oxygenna Typography Plugin: by Oxygenna.com – 1.1.2
Perfect Audience Retargeting: by PerfectAudience – 1.4
Regenerate Thumbnails: by Viper007Bond – 2.2.4
SendGrid: by SendGrid – 1.5.4
Simple 301 Redirects - Addon - Bulk CSV Uploader: by Ash Durham – 1.0.12
Simple 301 Redirects: by Scott Nellé – 1.06
Simple Custom CSS: by John Regan
Danny Van Kooten – 3.2

W3 Total Cache: by Frederick Townes – 0.9.4.1
WooCommerce Accepted Payment Methods: by jameskoster – 0.7.0
WooCommerce Conversion Tracking: by Tareq Hasan – 1.0
Follow-Up Emails: by 75nineteen Media LLC – 3.6.7 – 4.4.5 is available
WooCommerce Braintree Gateway: by SkyVerge – 2.2.0 – 2.3.2 is available
WooCommerce Google Analytics Integration: by WooThemes – 1.3.0
WooCommerce: by WooThemes – 2.3.9
WooSidebars: by WooThemes – 1.4.2
WP Robots Txt: by Christopher Davis – 1.1
XML Sitemap & Google News feeds: by RavanH – 4.4.1

### Settings ###

API Enabled: 
Taxes Enabled: –
Shipping Enabled: –
Force SSL: 
Currency: SGD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### WC Pages ###

Shop Base: #1095 - /shop/
Cart: #1096 - /cart/
Checkout: #1097 - /checkout/
My Account: #1098 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Swatch
Version: 1.6.1
Author URL: http://www.oxygenna.com
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: 

### Templates ###

Overrides: resumewriter/woocommerce/archive-product.php
resumewriter/woocommerce/cart/cart-empty.php
resumewriter/woocommerce/cart/cart-item-data.php
resumewriter/woocommerce/cart/cart-shipping.php version 2.1.0 is out of date. The core version is 2.3.0
resumewriter/woocommerce/cart/cart-totals.php version 2.1.0 is out of date. The core version is 2.3.6
resumewriter/woocommerce/cart/cart.php version 2.1.0 is out of date. The core version is 2.3.8
resumewriter/woocommerce/cart/cross-sells.php
resumewriter/woocommerce/cart/mini-cart.php
resumewriter/woocommerce/cart/shipping-calculator.php
resumewriter/woocommerce/checkout/cart-errors.php
resumewriter/woocommerce/checkout/form-billing.php
resumewriter/woocommerce/checkout/form-checkout.php version 2.0.0 is out of date. The core version is 2.3.0
resumewriter/woocommerce/checkout/form-coupon.php
resumewriter/woocommerce/checkout/form-login.php
resumewriter/woocommerce/checkout/form-pay.php
resumewriter/woocommerce/checkout/form-shipping.php version 2.1.2 is out of date. The core version is 2.2.0
resumewriter/woocommerce/checkout/review-order.php version 2.1.8 is out of date. The core version is 2.3.0
resumewriter/woocommerce/checkout/thankyou.php version 2.0.0 is out of date. The core version is 2.2.0
resumewriter/woocommerce/content-product.php
resumewriter/woocommerce/content-product_cat.php
resumewriter/woocommerce/content-single-product.php
resumewriter/woocommerce/content-widget-product.php
resumewriter/woocommerce/emails/customer-processing-order.php
resumewriter/woocommerce/global/breadcrumb.php version 1.6.4 is out of date. The core version is 2.3.0
resumewriter/woocommerce/global/form-login.php
resumewriter/woocommerce/global/quantity-input.php
resumewriter/woocommerce/global/sidebar.php
resumewriter/woocommerce/global/wrapper-end.php
resumewriter/woocommerce/global/wrapper-start.php
resumewriter/woocommerce/loop/add-to-cart.php
resumewriter/woocommerce/loop/loop-end.php
resumewriter/woocommerce/loop/loop-start.php
resumewriter/woocommerce/loop/no-products-found.php
resumewriter/woocommerce/loop/orderby.php version 2.0.0 is out of date. The core version is 2.2.0
resumewriter/woocommerce/loop/pagination.php version 2.0.0 is out of date. The core version is 2.2.2
resumewriter/woocommerce/loop/price.php
resumewriter/woocommerce/loop/rating.php
resumewriter/woocommerce/loop/result-count.php
resumewriter/woocommerce/loop/sale-flash.php
resumewriter/woocommerce/myaccount/form-add-payment-method.php
resumewriter/woocommerce/myaccount/form-edit-account.php version 1.6.4 is out of date. The core version is 2.2.7
resumewriter/woocommerce/myaccount/form-edit-address.php
resumewriter/woocommerce/myaccount/form-login.php version 2.1.0 is out of date. The core version is 2.2.6
resumewriter/woocommerce/myaccount/form-lost-password.php version 2.0.0 is out of date. The core version is 2.3.0
resumewriter/woocommerce/myaccount/my-account.php
resumewriter/woocommerce/myaccount/my-address.php version 2.0.0 is out of date. The core version is 2.2.0
resumewriter/woocommerce/myaccount/my-downloads.php
resumewriter/woocommerce/myaccount/my-orders.php version 2.1.0 is out of date. The core version is 2.2.0
resumewriter/woocommerce/myaccount/view-order.php version 2.0.15 is out of date. The core version is 2.2.0
resumewriter/woocommerce/notices/error.php
resumewriter/woocommerce/notices/notice.php
resumewriter/woocommerce/notices/success.php
resumewriter/woocommerce/order/form-tracking.php
resumewriter/woocommerce/order/order-details.php version 2.1.0 is out of date. The core version is 2.3.0
resumewriter/woocommerce/order/tracking.php version 1.6.4 is out of date. The core version is 2.2.0
resumewriter/woocommerce/single-product/add-to-cart/external.php
resumewriter/woocommerce/single-product/add-to-cart/grouped.php
resumewriter/woocommerce/single-product/add-to-cart/simple.php
resumewriter/woocommerce/single-product/add-to-cart/variable.php version 2.1.0 is out of date. The core version is 2.3.0
resumewriter/woocommerce/single-product/meta.php
resumewriter/woocommerce/single-product/price.php
resumewriter/woocommerce/single-product/product-attributes.php
resumewriter/woocommerce/single-product/product-image.php
resumewriter/woocommerce/single-product/product-thumbnails.php version 2.0.3 is out of date. The core version is 2.3.0
resumewriter/woocommerce/single-product/rating.php version 2.1.0 is out of date. The core version is 2.3.2
resumewriter/woocommerce/single-product/related.php
resumewriter/woocommerce/single-product/review.php
resumewriter/woocommerce/single-product/sale-flash.php
resumewriter/woocommerce/single-product/share.php
resumewriter/woocommerce/single-product/short-description.php
resumewriter/woocommerce/single-product/tabs/additional-information.php
resumewriter/woocommerce/single-product/tabs/description.php
resumewriter/woocommerce/single-product/tabs/tabs.php
resumewriter/woocommerce/single-product/title.php
resumewriter/woocommerce/single-product/up-sells.php
resumewriter/woocommerce/single-product-reviews.php version 2.1.0 is out of date. The core version is 2.3.2
resumewriter/woocommerce/single-product.php
resumewriter/woocommerce/taxonomy-product_cat.php
resumewriter/woocommerce/taxonomy-product_tag.php
